"use strict";

module.exports = {
	body: /^(PUT|POST|PATCH)$/,
	bodySplit: /&|=/,
	compress: /(javascript|json|text|xml|yaml)/,
	collection: /(.*)(\/.*)$/,
	def: /deflate/,
	dir: /\/$/,
	encodeForm: /application\/x-www-form-urlencoded/,
	encodeJson: /application\/json/,
	head: /^HEAD$/,
	"get": /^(GET|HEAD|OPTIONS)$/,
	getOnly: /^GET$/i,
	hasParam: /\/:(\w*)/,
	hasOrderByDesc: /(\?|&)order_by=desc/,
	hypermedia: /(([a-z]+(_)?)?id|url|uri)$/i,
	id: /^(_)?id$/i,
	indent: /application\/json;\sindent=(\d+)/,
	jsonWrap: /^[\[\{"]/,
	leading: /.*\//,
	leftBrace: /\(/,
	mimetype: /;.*/,
	modify: /DELETE|PATCH|POST|PUT/,
	options: /^OPTIONS$/,
	orderBy: /^order_by\=/,
	private: /private/,
	scheme: /^(\w+\:\/\/)|\//,
	trailing: /_.*$/,
	trailingS: /s$/,
	trailingSlash: /\/$/,
	trailingY: /y$/,
	unsortable: /boolean|number|string|void 0/
};
